#!/usr/bin/env bash
set -euo pipefail

echo "Battery thresholds:"
echo -n "Start: "
cat /sys/class/power_supply/BAT0/charge_control_start_threshold
echo -n "Stop:  "
cat /sys/class/power_supply/BAT0/charge_control_end_threshold
echo
echo "Battery state:"
echo -n "Status:   "
cat /sys/class/power_supply/BAT0/status
echo -n "Capacity: "
cat /sys/class/power_supply/BAT0/capacity
